# Generated by Django 5.0.6 on 2024-06-04 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=40)),
                ('prenom', models.CharField(max_length=70)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('photo', models.ImageField(upload_to='photos/')),
                ('numero_de_telephone', models.CharField(max_length=20)),
                ('code_barre', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
