# Generated by Django 5.0.6 on 2024-06-04 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
