# Generated by Django 5.0.6 on 2024-06-05 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Etudiant',
        ),
    ]
