# Generated by Django 5.0.6 on 2024-06-10 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_delete_etudiant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="photo",
            field=models.FileField(default=None, upload_to="photos/"),
            preserve_default=False,
        ),
    ]
