# Generated by Django 5.0.6 on 2024-06-10 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_alter_user_photo"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="User",
            new_name="Etudiant",
        ),
        migrations.CreateModel(
            name="Timedepointage",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("time", models.DateTimeField(auto_now_add=True)),
                (
                    "id_etudiant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.etudiant"
                    ),
                ),
            ],
        ),
    ]
